import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Highlight from "../components/Highlight";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/glenicon.png" />
      </Head>
      <Layout className="text-white">
        <div className="w-full max-w-[500px] md:max-w-[640px] lg:max-w-[840px] xl:max-w-[980px] 2xl:max-w-[1280px] flex items-center justify-center flex-col">
          <Hero />
          <Highlight />
        </div>
      </Layout>
    </div>
  );
}
